export default () => [
    { id: "1", label: "Face", name: "face", description: "Mặt", menu_id: "2" },
    { id: "2", label: "Lips & Nails", name: "lips-nails", description: "Môi và Nóng", menu_id: "2" },
    { id: "3", label: "Brushes & Tools", name: "brushes-tools", description: "Cây cọ vẽ, và dụng cụ", menu_id: "2" },
    { id: "4", label: "Moisturizers", name: "moisturizers", description: "Kem dưỡng ẩm", menu_id: "2" },
    { id: "5", label: "Masks", name: "masks", description: "Mặt nạ", menu_id: "2" },
    { id: "6", label: "Cleaners & Toners", name: "cleaners-toners", description: "Chất tẩy rữa, và nước hoa hồng", menu_id: "2" },
    { id: "7", label: "Face", name: "face", description: "Mặt", menu_id: "3" },
    { id: "8", label: "Eyes", name: "lips-nails", description: "Môi và Nóng", menu_id: "3" },
    { id: "9", label: "Brushes & Tools", name: "brushes-tools", description: "Cây cọ vẽ, và dụng cụ", menu_id: "3" },
    { id: "10", label: "Moisturizers", name: "moisturizers", description: "Kem dưỡng ẩm", menu_id: "3" },
    { id: "11", label: "Masks", name: "masks", description: "Mặt nạ", menu_id: "3" },
    { id: "12", label: "Cleaners & Toners", name: "cleaners-toners", description: "Chất tẩy rữa, và nước hoa hồng", menu_id: "3" },
    { id: "13", label: "Face", name: "face", description: "Mặt", menu_id: "4" },
    { id: "14", label: "Lips & Nails", name: "lips-nails", description: "Môi và Nóng", menu_id: "4" },
    { id: "14", label: "Brushes & Tools", name: "brushes-tools", description: "Cây cọ vẽ, và dụng cụ", menu_id: "4" },
    { id: "16", label: "Moisturizers", name: "moisturizers", description: "Kem dưỡng ẩm", menu_id: "4" },
    { id: "17", label: "Masks", name: "masks", description: "Mặt nạ", menu_id: "4" },
    { id: "18", label: "Cleaners & Toners", name: "cleaners-toners", description: "Chất tẩy rữa, và nước hoa hồng", menu_id: "4" },
    { id: "19", label: "Face", name: "face", description: "Mặt", menu_id: "5" },
    { id: "20", label: "Lips & Nails", name: "lips-nails", description: "Môi và Nóng", menu_id: "5" },
    { id: "21", label: "Brushes & Tools", name: "brushes-tools", description: "Cây cọ vẽ, và dụng cụ", menu_id: "5" },
    { id: "22", label: "Moisturizers", name: "moisturizers", description: "Kem dưỡng ẩm", menu_id: "5" },
    { id: "23", label: "Masks", name: "masks", description: "Mặt nạ", menu_id: "5" },
    { id: "24", label: "Cleaners & Toners", name: "cleaners-toners", description: "Chất tẩy rữa, và nước hoa hồng", menu_id: "5" }
];