export default () => [
    { id: "1", collection_id: "1", label: "Foundation", name: "foundation", description: "Mặt" },
    { id: "2", collection_id: "1", label: "Highlingting", name: "high-lingting", description: "Môi và Nóng" },
    { id: "3", collection_id: "2", label: "Lips Gloss", name: "lips-gloss", description: "Cây cọ vẽ, và dụng cụ" },
    { id: "4", collection_id: "2", label: "Lips Linear", name: "lips-linear", description: "Kem dưỡng ẩm" },
    { id: "5", collection_id: "3", label: "Makeup Brushes", name: "makeup-brushes", description: "Mặt nạ" },
    { id: "6", collection_id: "3", label: "Makeup Tools", name: "makeup-tools", description: "Chất tẩy rữa, và nước hoa hồng" },
    { id: "7", collection_id: "4", label: "Day Creams", name: "day-creams", description: "Mặt nạ" },
    { id: "8", collection_id: "4", label: "Nigh Creams", name: "nigh-creams", description: "Chất tẩy rữa, và nước hoa hồng" },
    { id: "9", collection_id: "5", label: "Clay Mask", name: "clay-mask", description: "Mặt nạ" },
    { id: "10", collection_id: "5", label: "Nigh Masks", name: "nigh-maks", description: "Chất tẩy rữa, và nước hoa hồng" },
    { id: "11", collection_id: "6", label: "Cleansers", name: "cleansers", description: "Mặt nạ" },
    { id: "12", collection_id: "6", label: "Toners", name: "toners", description: "Chất tẩy rữa, và nước hoa hồng" },
    { id: "13", collection_id: "7", label: "Cleansers", name: "cleansers", description: "Mặt nạ" },
    { id: "14", collection_id: "7", label: "Toners", name: "toners", description: "Chất tẩy rữa, và nước hoa hồng" },
    { id: "15", collection_id: "8", label: "Clay Mask", name: "clay-mask", description: "Mặt nạ" },
    { id: "16", collection_id: "8", label: "Nigh Masks", name: "nigh-maks", description: "Chất tẩy rữa, và nước hoa hồng" },
    { id: "17", collection_id: "9", label: "Cleansers", name: "cleansers", description: "Mặt nạ" },
    { id: "18", collection_id: "9", label: "Toners", name: "toners", description: "Chất tẩy rữa, và nước hoa hồng" },
    { id: "19", collection_id: "10", label: "Cleansers", name: "cleansers", description: "Mặt nạ" },
    { id: "20", collection_id: "10", label: "Toners", name: "toners", description: "Chất tẩy rữa, và nước hoa hồng" },
    { id: "21", collection_id: "11", label: "Foundation", name: "foundation", description: "Mặt" },
    { id: "22", collection_id: "11", label: "Highlingting", name: "high-lingting", description: "Môi và Nóng" },
    { id: "23", collection_id: "12", label: "Lips Gloss", name: "lips-gloss", description: "Cây cọ vẽ, và dụng cụ" },
    { id: "24", collection_id: "12", label: "Lips Linear", name: "lips-linear", description: "Kem dưỡng ẩm" },
    { id: "25", collection_id: "13", label: "Makeup Brushes", name: "makeup-brushes", description: "Mặt nạ" },
    { id: "26", collection_id: "13", label: "Makeup Tools", name: "makeup-tools", description: "Chất tẩy rữa, và nước hoa hồng" },
    { id: "27", collection_id: "14", label: "Day Creams", name: "day-creams", description: "Mặt nạ" },
    { id: "28", collection_id: "14", label: "Nigh Creams", name: "nigh-creams", description: "Chất tẩy rữa, và nước hoa hồng" },
    { id: "29", collection_id: "15", label: "Clay Mask", name: "clay-mask", description: "Mặt nạ" },
    { id: "30", collection_id: "15", label: "Nigh Masks", name: "nigh-maks", description: "Chất tẩy rữa, và nước hoa hồng" },
    { id: "31", collection_id: "16", label: "Cleansers", name: "cleansers", description: "Mặt nạ" },
    { id: "32", collection_id: "16", label: "Toners", name: "toners", description: "Chất tẩy rữa, và nước hoa hồng" },
    { id: "33", collection_id: "17", label: "Cleansers", name: "cleansers", description: "Mặt nạ" },
    { id: "34", collection_id: "17", label: "Toners", name: "toners", description: "Chất tẩy rữa, và nước hoa hồng" },
    { id: "35", collection_id: "18", label: "Clay Mask", name: "clay-mask", description: "Mặt nạ" },
    { id: "36", collection_id: "18", label: "Nigh Masks", name: "nigh-maks", description: "Chất tẩy rữa, và nước hoa hồng" },
    { id: "37", collection_id: "19", label: "Cleansers", name: "cleansers", description: "Mặt nạ" },
    { id: "38", collection_id: "19", label: "Toners", name: "toners", description: "Chất tẩy rữa, và nước hoa hồng" },
    { id: "39", collection_id: "20", label: "Cleansers", name: "cleansers", description: "Mặt nạ" },
    { id: "40", collection_id: "20", label: "Toners", name: "toners", description: "Chất tẩy rữa, và nước hoa hồng" },
    { id: "41", collection_id: "21", label: "Foundation", name: "foundation", description: "Mặt" },
    { id: "42", collection_id: "21", label: "Highlingting", name: "high-lingting", description: "Môi và Nóng" },
    { id: "43", collection_id: "22", label: "Lips Gloss", name: "lips-gloss", description: "Cây cọ vẽ, và dụng cụ" },
    { id: "44", collection_id: "22", label: "Lips Linear", name: "lips-linear", description: "Kem dưỡng ẩm" },
    { id: "45", collection_id: "23", label: "Makeup Tools", name: "makeup-tools", description: "Chất tẩy rữa, và nước hoa hồng" },
    { id: "46", collection_id: "23", label: "Makeup Brushes", name: "makeup-brushes", description: "Mặt nạ" },
    { id: "47", collection_id: "24", label: "Nigh Creams", name: "nigh-creams", description: "Chất tẩy rữa, và nước hoa hồng" },
    { id: "48", collection_id: "24", label: "Day Creams", name: "day-creams", description: "Mặt nạ" }
];